version: "3"
services:
  db:
    image: postgres
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  # webserver:
  #   build: Docker/nginx
  #   ports:
  #     - 9000:443